{% set version = "0.2.4" %}

package:
  name: mpl-probscale
  version: {{ version }}

source:
  url: https://github.com/matplotlib/mpl-probscale/archive/v{{ version }}.tar.gz
  sha256: bf28b9e0f75dba4ad833590aabbfb3196785c1e1fc755245ec350f970caa16a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    # not really needed but the basic import imports the tests and needs this
    - pytest

test:
  imports:
    - probscale

about:
  home: http://matplotlib.org/mpl-probscale/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Probability scales for matplotlib

extra:
  recipe-maintainers:
    - phobson
