{% set version = "0.2.3" %}

package:
  name: mpl-probscale
  version: {{ version }}

source:
  url: https://github.com/matplotlib/mpl-probscale/archive/v{{ version }}.tar.gz
  sha256: 87e4ee63f484a9581ff06ae888e94827ea583d8f556ae5182bab85e714c0e5c1

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib
    # not really needed but the basic import imports the tests and needs this
    - pytest

test:
  imports:
    - probscale

about:
  home: http://matplotlib.org/mpl-probscale/
  license:  BSD-3-Clause
  license_file: LICENSE
  summary: 'Probability scales for matplotlib'

extra:
  recipe-maintainers:
    - phobson
