{% set version = "0.2.3" %}


package:
  name: mpl-probscale
  version: {{ version }}

source:
  fn: mpl-probscale-{{ version }}.tar.gz
  url: https://github.com/matplotlib/mpl-probscale/archive/v{{ version }}.tar.gz
  sha256: 87e4ee63f484a9581ff06ae888e94827ea583d8f556ae5182bab85e714c0e5c1

build:
  number: 1
  script: pip install . --no-deps

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib
    - pytest

test:
  imports:
    - probscale
  requires:
    - mock  # [py27]
    - pytest
    - pytest-mpl
    - scipy
  commands:
    - python -c "import sys; import matplotlib as mpl; mpl.use('agg'); import probscale as ps; sys.exit(ps.test())"

about:
  home: http://matplotlib.org/mpl-probscale/
  license:  BSD 3-clause
  license_file: LICENSE
  summary: 'Probability scales for matplotlib.'

extra:
  recipe-maintainers:
    - phobson
