{% set version = "0.2.2" %}


package:
  name: mpl-probscale
  version: {{ version }}

source:
    git_url: https://github.com/phobson/mpl-probscale.git
    git_tag: v{{ version }}


build:
  number: 0
  script: pip install . --no-deps

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - pytest

test:
  imports:
    - probscale

  requires:
    - mock  # [py27]
    - pytest
    - pytest-mpl
    - scipy

  commands:
    - python -c "import sys; import matplotlib as mpl; mpl.use('agg'); import probscale as ps; sys.exit(ps.test('--mpl'))"

about:
  home: http://phobson.github.io/mpl-probscale/
  license:  BSD 3-clause
  summary: 'Probability scales for matplotlib.'

extra:
    recipe-maintainers:
        - phobson
