appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NQg6K0vXeu2FVNbhZolRAXIHks9g6MJil+ZEXhwCUkUQKvWuwWklDlwMxSN3Rx++wgl16QbXSEnogL46/B7+n97XhLJ2zMqSA1cHOtBc5qpqGInJaeZGyCV3bp1tQN/R4cDZnmHPRTLHqmV+ILIs1UMEKrngQMHKF/x0miy9ErfAN33G4+jEmyz8+WJmiu1A8melRnniUyI/NJSqBb1ZKA/yBXTWBU2Qt81UVLoknNflX5/1CyhEkPCRkmyvEzH7nzmgT1UeZww8FIuqD8YArVv0fK+HWlJlgEwfixo0x52sW5AGh7CRAEFSC6Fz4zbM3w3kg3w+vwzK5Naq2l3SJzfmhXXo75m7WmLfT1RuJTSnh98nJcsVzhYhwNp5YaMT3CRj/twAztIXuVd2noFn0AOJsES7R3Uz1iUUR2aIopqTGYjHXDbdLR+cG25ui6pk9LnND+BryMalYUeLJP7R3aiWZCdwBlw5SKOygARgxI7oiGrgdGc02ouhxpxnO0nIVpPinnQElM55JH5bue6lhwr2+RmtgiiS5rZWxe4WnLPXp2NaP+yOik+MKOiuMBGQUdy94CqPZGPve/nXKA28R+QehVhfX3Bmjmw1urfYSV4z9i5QZK/JazZvME7PQM+rvu3htOE6YN8JQa/wYQ4VYCgwUIVHjjoT11UlmU8i/i8=}
conda_forge_output_validation: true
