travis:
  secure:
    BINSTAR_TOKEN: wMlnbiFWrdXm4J87ADPYJgxXJ6zWhutzzgHwUjV1tTIV6bOZiIYyFvEYd570v0NJwwvGBA3GalrbPNy4kLTZKd6UQc4hYCs5tNacapPE5UBD7NJ4WFJeR+mx25OQmdMlzzFkWCBruqfQ2EGwv6+D+YjconsqsPIAMsMyAnvPDdWnaRjMplYlUGDkR9ypkVxnAIv1jmRuarqpOMxAk3LSJc8cXHs5fP911QZL8mWa5nDnwQdouOLje8CZw/Kz8iTw3hnX8yhhip+zfijfdpNqHKRvWJo8sBXtT2rb2HfzoUVgEC9SZRA2iPzI/Drdd7ouhk98q+BHOvdASLBXJRmQaN1/DoqwNvfS3INaDeCzHjXxTsQra12ua/yGK998/jWm9BD9SUWxjP4mpDp0Nuy3J44lQATuriSRzXDPyhTuJGs70V2tQ84eoDqXIQi45BFEg8ZSddGhHGJ1T/FlkaAmCRnxpUXbMNA8c6jr5GYa4z+2Tocpipa8zjo+ZxtfxUOFFGFX9v6DgSNxLpbe7aRjETIEs0vn4yhAj03mDFJmgf+AVOKMBBTpJfk4SD/FhMyMmFfJCrH3CvTkz/9h+zIWwd8LjuXq+u0JPiArQzYLAM7ysZXxBPfhef4/jWuERnF5+Mt8PwXMscpV/D+G3fjxiEdg0tKmlJjS+mwCqLnbTsw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
